version: "3.9"
services:
  postgres:
    container_name: postgres-server
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=musicshopdb
    ports:
      - "5432:5432"
    networks:
      - musicshop_backend
    env_file:
      - .env
  jms-provider:
    container_name: jms-provider
    image: rmohr/activemq:5.15.9-alpine
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - musicshop_backend
  backend:
    container_name: musicshop-backend
    build: .
    ports:
      - ${RMI_PORT}:${RMI_PORT}
    networks:
      - musicshop_backend
    links:
      - postgres
      - jms-provider
    env_file:
      - .env

networks:
  musicshop_backend:
    driver: bridge
