apiVersion: apps/v1
kind: Deployment
metadata:
  name: jms-provider
spec:
  selector:
    matchLabels:
      app: jms-provider
  template:
    metadata:
      name: jms-provider
      labels:
        app: jms-provider
    spec:
      containers:
        - name: jms-provider
          image: webcenter/activemq:latest
          env:
            - name: ACTIVEMQ_ADMIN_LOGIN
              valueFrom:
                secretKeyRef:
                  name: monolith-secret
                  key: activemq_username
                  optional: false
            - name: ACTIVEMQ_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: monolith-secret
                  key: activemq_password
                  optional: false
            - name: ACTIVEMQ_STATIC_TOPICS
              value: "Orders;Pop;Metal;Rock;Electronic;Grunge;Hip-Hop;Hard Rock"
          ports:
            - name: activemq1
              containerPort: 61616
            - name: activemq2
              containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: jms-provider
spec:
  type: LoadBalancer
  selector:
    app: jms-provider
  ports:
    - name: activemq1
      port: 61616
      targetPort: activemq1
    - name: activemq2
      port: 8161
      targetPort: activemq2
